---
title: "Data Exploration"
author: "Vanessa Machuca"
date: "4/28/2018"
output: pdf_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(loopr)
```

I will know graph gas emissions over time, to get a sense of any patterns that may be present.

```{r}
compost_GHG <- read_csv("~/Desktop/MATH183_Modeling/Project/compost/compost-GHG.csv")
```

I am interested in O2 and NH3 levels in particular. 

```{r}
ggplot(compost_GHG,aes(x=`Julian Day`,colour=`Chamber Number`))+geom_point(aes(y=`Mean NH3 (ppm)`))

ggplot(compost_GHG,aes(x=`Julian Day`,colour=`Chamber Number`))+ geom_point(aes(y=`Mean N2O (ppm)`))

ggplot(compost_GHG,aes(x=`Julian Day`,colour=`Chamber Number`))+ geom_point(aes(y=`Mean H2O (ppm)`))

ggplot(compost_GHG,aes(x=`Julian Day`,colour=`Chamber Number`))+ geom_point(aes(y=`Cav. Temperature (K)`))

ggplot(compost_GHG,aes(x=`Julian Day`,colour=`Chamber Number`))+ geom_point(aes(y=`Chamber Temperature (K)`))

```

